# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "527ed7fe1acd787fb453f0604af040df"
name = "Uber"
application_url = "https://actors-profession-christina-leg.trycloudflare.com"
embedded = true

[build]
automatically_update_urls_on_dev = true
dev_store_url = "uber-infy.myshopify.com"
include_config_on_deploy = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_checkouts,read_orders,read_products,read_script_tags,read_shipping,write_checkouts,write_orders,write_products,write_script_tags,write_shipping"

[auth]
redirect_urls = [
  "https://actors-profession-christina-leg.trycloudflare.com/auth/callback",
  "https://actors-profession-christina-leg.trycloudflare.com/auth/shopify/callback",
  "https://actors-profession-christina-leg.trycloudflare.com/api/auth/callback"
]

[webhooks]
api_version = "2024-04"

[pos]
embedded = false
